version: '3.3'

services:
    #MySQL Service
    db:
        image: mysql
        container_name: wp_db
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
            - app-network
    
    #Wordpress Service
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        container_name: wp_apps
        ports:
            - "8000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge

volumes:
    db_data: {}
    